name: Translations

on: 
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths:
      - '**.po'

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.1.12"
  POETRY_HOME: "~/.poetry"

concurrency:
  group: translations-${{ github.event.pull_request.number }}
  cancel-in-progress: false # Let previous job complete

jobs:
  upload-to-lokalise:
    name: Upload to Lokalise
    runs-on: ubuntu-latest
    # Only run this if the PR is flagged with needs-translations. We do this
    # because we don't want to upload work-in-progress translations until the
    # developer marks the PR as ready.
    if: contains(github.event.pull_request.labels.*.name, 'needs translations')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Lokalise CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
      - name: Upload .po files
        run: |
          languages=("en", "nb")
          for language in "${languages[@]}"; do
              lokalise2 \
                --token "${{ secrets.LOKALISE_API_TOKEN }}" \
                --project-id "${{ secrets.LOKALISE_PROJECT_ID }}" \
                file upload \
                --file "project/locale/${language}/LC_MESSAGES/django.po" \
                --lang-iso "${language}" \
                --convert-placeholders=false \
                --tags "user:${{ github.event.pull_request.user.login }},pr:${{ github.event.pull_request.number }}"
          done
      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          script: |
            const markerComment = "<!-- translations uploaded to lokalise -->";

            const issue_number = context.payload.pull_request.number;
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });
            const comment = comments.find(comment => comment.body.includes(markerComment));
            const runLink = `${context.serverUrl}/${context.payload.repository.full_name}/actions/runs/${context.runId}`;

            const commentText = `
            Your translations have been uploaded to Lokalise. We will notify you when the translations are ready.

            <details>
            <summary>About this bot</summary>
            This comment was posted by <a href="${runLink}">this workflow</a>.
            </details>

            ${markerComment}
            `;

            if (comment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                body: commentText,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: commentText,
              });
            }

  comment:
    name: Comment on PR
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'needs translations') }}
    steps:
      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          script: |
            const uploadedMarkerComment = "<!-- translations uploaded to lokalise -->";
            const markerComment = "<!-- how to upload to lokalise -->";

            const issue_number = context.payload.pull_request.number;
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });

            // Only comment if we haven't already done so
            if (
              comments.some(comment => comment.body.includes(markerComment) || comment.body.includes(uploadedMarkerComment))
            ) {
              return;
            }

            const runLink = `${context.serverUrl}/${context.payload.repository.full_name}/actions/runs/${context.runId}`;

            const commentText = `
            Howdy 👋 It looks like this pull request contains changes to translations. When your PR is ready please add the \`needs translations\` label to the PR. The translations will then be automatically uploaded to Lokalise.

            <details>
            <summary>About this bot</summary>
            This comment was posted by <a href="${runLink}">this workflow</a>.
            </details>

            ${markerComment}
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: commentText,
            });
